# Generated by Django 3.2.7 on 2021-11-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(verbose_name=-4)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
                ('endDate', models.DateField()),
                ('createDate', models.DateField()),
                ('bid', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('category', models.ManyToManyField(to='main_app.Category')),
            ],
        ),
    ]
