# Generated by Django 3.2.8 on 2021-11-08 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211108_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
    ]
