# Generated by Django 3.2.8 on 2021-11-09 00:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_task_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
