# Generated by Django 3.2.8 on 2021-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211109_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('I', 'Intermediate'), ('H', 'Hard')], default='E', max_length=1, verbose_name='difficulty selection'),
        ),
    ]
